language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - libc6:i386 # these two packages are needed by the launch4j maven plugin to work
    - libstdc++6:i386
before_install:
- mvn clean # this actually installs a dependency
before_deploy:
- mvn package -DskipTests=true -f travis-ci/wrapper-for-mac/pom.xml
- mvn package -DskipTests=true -f travis-ci/wrapper-for-windows/pom.xml
- bash travis-ci/scripts/zip-and-move-wrapper-for-mac.sh
- export filename=$(bash travis-ci/scripts/get-amidst-filename.sh)
deploy:
  provider: releases
  api_key: # this encrypted token is only readable by travis ci to access the github accout to attach the files to the created tag/release
    secure: F1bVvI4MuNosAozor3CFkeeq8ncE6FaF/lSub+HpmnFvrZprXEfzVvzZj9eh98PPOg5U6/+fsN3vR3hvStZ9u1BXBTFfiKxZZb1xFlnzkX1JpUJJYhARUYNHOMwXxU32syHs40j/ABGU27teLnuwSHcVQGGtxqX2ka5guCxzJnw68B8EgB0gGv7hN0iRocpbpA5uyAtoGyLBIebYQ5r6Bda/8HW1OshW+xNfPc1lcaC2kd0v5OgxjlyCodi4JsJQvdCZOvoMwORjpUamBgVhPS82vqVVONCfkT+j+sCgT5JZsjHjGS7MnSXK4y2Zyt1ghf2MY6gwx5QGmjZnQnTU6agQQ9zLNSW780ugbQxylWLrPQsTTWGqzS4G/rYh7iRJXHw6jJA9FgRGkE14/leox8a3s2QvYTbMgdeMekqw0YCgs4KnxrZYb1edGTOzs3f8jgMofr8EjOWjzDayB4kc+Yp5++BjtTUV6X+jMNKI1tmgOBUrSFQFqt0uvsDkHhcIuCDEHo04ubNPwJhnKl7zkdoVrALrPuTAQI68tfhWuqgP+8FvSAB9Tpw4k3rHdae+LFnG+7q2ktxRlrlV6WevaEFUz1QsokyRAB1VrcEjWEfn87zuBpSDU5NPgs5l0d32QAeP9XbXn+Pp7XGErhDcbHH+C0C9EvTy57sAAf/7ujM=
  file:
  - "target/${filename}.jar"
  - "target/${filename}.zip"
  - "target/${filename}.exe"
  skip_cleanup: true
  on:
    repo: treer/amidstest
    branch: releases
    tags: true
