language: java
jdk:
- openjdk8
addons:
  apt:
    packages:
    - libc6:i386 # these two packages are needed by the launch4j maven plugin to work
    - libstdc++6:i386
before_install:
- mvn clean # this actually installs a dependency
before_deploy:
- mvn package -DskipTests=true -f travis-ci/wrapper-for-mac/pom.xml
- mvn package -DskipTests=true -f travis-ci/wrapper-for-windows/pom.xml
- bash travis-ci/scripts/zip-and-move-wrapper-for-mac.sh
- export filename=$(bash travis-ci/scripts/get-amidst-filename.sh)
deploy:
  provider: releases
  api_key: # this encrypted token is only readable by travis ci to access the github accout to attach the files to the created tag/release
    secure: ZqjcGz5yL41o70rjKMLQJNDQgR6dDbQh53BC5AWmokAYFcxjtshZBFVIifrvO4SfBnBfvaYsGRl2xy2qNqXoUNbNFw151GaZPbvdYyeG6W0WIWyrlWG5U4NS3fjXXq6Gh/+8hTWRiRDHGiIRNx9QdhqyjazkjepjpZa37WcYu5o/DUrqSTnqv2c/9RuDYRvmVxDktnwfUKbh+uJMW03oPDhvyqm2cWQ2L8BSlCPdsdC5Pl5qEuDwTb+9S6r5oiF2usnwzfgIb4YGGWtCbOgWmsr3NJ65v9bY2iEiZp/V+b6PfCN44jyydkBvnuuLMSvQmSYpgxxqC2yEADSgVBwikwbdikEmU+t5eGGUITZNpwPvqUPYfZbmH+KSSKIV+HRDidaEF43YJcMNuJowu37XgdQKke75gi5EzwvujZhIpUBbLZSV318spwYWbtrj9xPqrEIhmV+MQqO9gjxMDhGH+psQt01D5V2vqagMCRtc2h5SykRyeZekdqHW7SHm32H5CJ4267AjAPkiENTCrCaQJmemclLIgAk8AKCDG/mn68Uv2EOg0ZHU1sPaLcDFbhOiBzwB1feo+1xXRPzceqnoBDVi6+o+qyVWuBsxTsxLkvvRCBy0166sBpsUzFBUePYlhR5ETc+h65Q554xu/jQtxno/bJ1EDtSYWIrYloFSisE=
  file:
  - "target/${filename}.jar"
  - "target/${filename}.zip"
  - "target/${filename}.exe"
  skip_cleanup: true
  on:
    repo: Treer/Amidst-for-Minetest
    branch: releases
    tags: true
